apiVersion: apps/v1
kind: Deployment
metadata:
  name: underwriter-deploy
  labels:
    app: underwriter-ms

spec:
  replicas: 1
  selector:
    matchLabels:
      app: underwriter-ms
  template:
    metadata:
      labels:
        app: underwriter-ms
    spec:
      containers:
        - name: underwriter-ms
          image: myates7748/aline-my:underwriter-ms
          ports:
            - containerPort: 8071
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: aline-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: aline-config
                  key: DB_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aline-secret
                  key: MYSQL_PASSWORD
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: aline-config
                  key: DB_PORT
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: aline-secret
                  key: MYSQL_USER
            - name: ENCRYPT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aline-secret
                  key: ENCRYPT_SECRET_KEY
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aline-secret
                  key: JWT_SECRET_KEY
  
---

apiVersion: v1
kind: Service
metadata:
  name: underwriter-service
spec:
  type: Nodeport
  selector:
    app: underwriter-ms
  ports:
    - protocol: TCP
      port: 8071
      targetPort: 8071
      nodePort: 30871
